apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  selector:
    matchLabels:
      app: pythondeployment
  replicas: 1
  template:
    metadata:
      labels:
        app: pythondeployment
    spec:
      containers:
      - name: pythondeployment
        image: mcr.microsoft.com/devcontainers/python:3.11
        command: ["tail"]
        args: ["-f", "/dev/null"] 